import Link from 'next/link';
import { getPosts, getCategories, postCategories, plainText, type Post, type Category } from './lib/wordpress';
export default async function Home({ searchParams }: { searchParams: Promise<{ category?: string | string[] }> }) {
  const query = await searchParams;
  const selectedSlug = typeof query.category === 'string' ? query.category : undefined;
  let posts: Post[] = []; let categories: Category[] = []; let unavailable = false;
  let selected: Category | undefined;
  let unknownCategory = false;
  try {
    categories = await getCategories();
    selected = categories.find(category => category.slug === selectedSlug);
    unknownCategory = Boolean(selectedSlug && !selected);
    if (!unknownCategory) posts = await getPosts(undefined, selected?.id);
  } catch { unavailable = true; }
  return <><section className="hero"><div><p className="eyebrow">ЗНАННЯ, ЯКІ СТАЮТЬ ПРАКТИКОЮ</p><h1>Від першого питання<br/>до власного <em>проєкту.</em></h1><p className="lead">Вивчай веброзробку крок за кроком. Зрозумілі пояснення, практичні приклади та матеріали, до яких хочеться повернутися.</p><a className="button" href="#materials">Почати навчання <span>↗</span></a><p className="hero-note">Власний темп. Реальні знання.</p></div><div className="illustration" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="floating tag-api">API ↗</span><span className="floating tag-code">&lt;/&gt;</span><div className="book"><span>ТВОЯ НАСТУПНА<br/>ВЕЛИКА ІДЕЯ</span><strong>Починається<br/>з цікавості.</strong><div className="book-line"/><small>STUDYHUB / 01</small></div><span className="spark">✳</span></div></section><section className="materials" id="materials"><div className="section-heading"><div><p className="eyebrow">БІБЛІОТЕКА ЗНАНЬ</p><h2>Почни з цікавого</h2></div><span className="pill">{selected ? plainText(selected.name) : 'Усі теми'}</span></div><nav className="category-filters" aria-label="Категорії матеріалів"><Link href="/#materials" className={`filter${!selectedSlug ? ' active' : ''}`} aria-current={!selectedSlug ? 'page' : undefined}>Усі</Link>{categories.map(category => <Link key={category.id} href={`/?category=${encodeURIComponent(category.slug)}#materials`} className={`filter${selected?.id === category.id ? ' active' : ''}`} aria-current={selected?.id === category.id ? 'page' : undefined}>{plainText(category.name)}</Link>)}</nav>{unavailable ? <div role="status" className="notice">Матеріали тимчасово недоступні. Спробуй оновити сторінку трохи пізніше.</div> : posts.length === 0 ? <p className="notice">{unknownCategory ? 'Такої категорії немає або вона ще не має опублікованих матеріалів. Обери іншу категорію.' : 'У цій категорії поки немає матеріалів.'}</p> : <div className="cards">{posts.map((post, i) => <Link className="card" href={`/materialy/${post.slug}`} key={post.id}><div className="card-art"><span className="card-number">{String(i + 1).padStart(2, '0')}</span><span className="code-mark">{'{ }'}</span><span className="art-label">ЗРОЗУМІЙ · СПРОБУЙ · СТВОРИ</span></div><div className="card-body"><p className="card-meta">{postCategories(post).map(category => plainText(category.name)).join(' · ') || 'МАТЕРІАЛ'} · {new Date(post.date).toLocaleDateString('uk-UA')}</p><h3>{plainText(post.title.rendered)}</h3><p>{plainText(post.excerpt.rendered)}</p><span className="read-link">Читати матеріал <span>↗</span></span></div></Link>)}</div>}</section><section className="about" id="about"><span className="about-icon">✳</span><div><p className="eyebrow">ПРО STUDYHUB</p><h2>Не просто читати.<br/>Розуміти й застосовувати.</h2></div><p>Цей портал створений для студентів, які хочуть розібратися у вебтехнологіях. Починаємо з основ і пов’язуємо кожну нову ідею з практикою.</p></section></>;
}
