import assert from 'node:assert/strict';
const api = process.env.WORDPRESS_API_URL || 'http://127.0.0.1:8080/wp-json/wp/v2';
const site = process.env.SITE_URL || 'http://127.0.0.1:3000';
const postsResponse = await fetch(`${api}/posts?slug=yak-pratsiuie-cms`);
assert.equal(postsResponse.status, 200);
const [post] = await postsResponse.json();
assert.ok(post?.id, 'Seed article must exist in the real CMS');
const home = await fetch(site);
assert.equal(home.status, 200);
assert.ok((await home.text()).includes(`/materialy/${post.slug}`), 'Homepage must link to CMS article');
const article = await fetch(`${site}/materialy/${post.slug}`);
assert.equal(article.status, 200);
assert.ok((await article.text()).includes('REST API передає дані'), 'Article must render CMS content');
assert.equal((await fetch(`${site}/materialy/does-not-exist-studyhub`)).status, 404);
const drafts = await fetch(`${api}/posts?status=draft`);
assert.equal(drafts.status, 400);
assert.equal((await drafts.json()).data.details.status.code, 'rest_forbidden_status', 'CMS must explicitly forbid draft access');
const create = await fetch(`${api}/posts`, {method:'POST', headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Unauthorized smoke test',status:'draft'})});
assert.equal(create.status, 401, 'Anonymous visitors must not create posts');
console.log('PASS: CMS article, homepage, article content, 404, private drafts, write protection (6 checks).');
