import assert from 'node:assert/strict';
const api = process.env.WORDPRESS_API_URL || 'http://127.0.0.1:8080/wp-json/wp/v2';
const site = process.env.SITE_URL || 'http://127.0.0.1:3000';
const postsResponse = await fetch(`${api}/posts?slug=yak-pratsiuie-cms`);
assert.equal(postsResponse.status, 200);
const [post] = await postsResponse.json();
assert.ok(post?.id, 'Seed article must exist in the real CMS');
const home = await fetch(site);
assert.equal(home.status, 200);
assert.ok((await home.text()).includes(`/materialy/${post.slug}`), 'Homepage must link to CMS article');
const article = await fetch(`${site}/materialy/${post.slug}`);
assert.equal(article.status, 200);
assert.ok((await article.text()).includes('REST API передає дані'), 'Article must render CMS content');
assert.equal((await fetch(`${site}/materialy/does-not-exist-studyhub`)).status, 404);
const drafts = await fetch(`${api}/posts?status=draft`);
assert.equal(drafts.status, 400);
assert.equal((await drafts.json()).data.details.status.code, 'rest_forbidden_status', 'CMS must explicitly forbid draft access');
const create = await fetch(`${api}/posts`, {method:'POST', headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Unauthorized smoke test',status:'draft'})});
assert.equal(create.status, 401, 'Anonymous visitors must not create posts');
const categoryId = post.categories[0];
const categoryResponse = await fetch(`${api}/categories/${categoryId}`);
assert.equal(categoryResponse.status, 200);
const category = await categoryResponse.json();
const filtered = await fetch(`${site}/?category=${encodeURIComponent(category.slug)}`);
assert.equal(filtered.status, 200);
const filteredHtml = await filtered.text();
assert.ok(filteredHtml.includes(`/materialy/${post.slug}`), 'Category filter must include matching CMS article');
assert.ok(filteredHtml.includes('aria-current="page"'), 'Selected category must be marked active');
const allResponse = await fetch(`${api}/posts?per_page=100`);
const allPosts = await allResponse.json();
for (const other of allPosts.filter(item => !item.categories.includes(categoryId))) {
  assert.ok(!filteredHtml.includes(`/materialy/${other.slug}`), 'Category filter must exclude other articles');
}
const missingCategory = await fetch(`${site}/?category=does-not-exist-studyhub`);
assert.equal(missingCategory.status, 200);
assert.ok((await missingCategory.text()).includes('Такої категорії немає'), 'Unknown category must show an explicit empty state');
const searchPage = await fetch(`${site}/?q=${encodeURIComponent('REST API')}&category=${encodeURIComponent(category.slug)}`);
assert.equal(searchPage.status, 200);
const searchHtml = await searchPage.text();
assert.ok(searchHtml.includes(`/materialy/${post.slug}`), 'Search must find matching article inside selected category');
assert.ok(searchHtml.includes('name="category"'), 'Search form must preserve category');
assert.ok(searchHtml.includes('q=REST+API'), 'Category links must preserve search');
const emptySearch = await fetch(`${site}/?q=studyhub-no-match-987654321`);
const emptyHtml = await emptySearch.text();
assert.ok(emptyHtml.includes('За цим запитом матеріалів не знайдено'), 'Unmatched search must display empty state');
assert.ok(!emptyHtml.includes(`/materialy/${post.slug}`), 'Unmatched search must not return unrelated articles');
console.log('PASS: CMS article, homepage, article content, 404, private drafts, write protection, category inclusion/exclusion, active filter, unknown category, search, combined filters, empty search.');
